// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMWvm8hw0-oiW0XXp1Tet2f4aO5h_iLqs',
    appId: '1:618030859014:web:5a61a91d0683bf6a881487',
    messagingSenderId: '618030859014',
    projectId: 'orb-app-b04b6',
    authDomain: 'orb-app-b04b6.firebaseapp.com',
    storageBucket: 'orb-app-b04b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIGPzrHXsbo_oR_wg0Mrdw5yT0ZexediE',
    appId: '1:618030859014:android:e41bf027f2f72925881487',
    messagingSenderId: '618030859014',
    projectId: 'orb-app-b04b6',
    storageBucket: 'orb-app-b04b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ZcoA_9REXlLXSOYskuMVF6SW3VDaEg8',
    appId: '1:618030859014:ios:4ad5ec9386d9a5aa881487',
    messagingSenderId: '618030859014',
    projectId: 'orb-app-b04b6',
    storageBucket: 'orb-app-b04b6.firebasestorage.app',
    iosBundleId: 'com.example.orbApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0ZcoA_9REXlLXSOYskuMVF6SW3VDaEg8',
    appId: '1:618030859014:ios:4ad5ec9386d9a5aa881487',
    messagingSenderId: '618030859014',
    projectId: 'orb-app-b04b6',
    storageBucket: 'orb-app-b04b6.firebasestorage.app',
    iosBundleId: 'com.example.orbApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMWvm8hw0-oiW0XXp1Tet2f4aO5h_iLqs',
    appId: '1:618030859014:web:9b1668b62f5c6fa1881487',
    messagingSenderId: '618030859014',
    projectId: 'orb-app-b04b6',
    authDomain: 'orb-app-b04b6.firebaseapp.com',
    storageBucket: 'orb-app-b04b6.firebasestorage.app',
  );
}
