# The cloud Mac needs this path to understand Flutter commands
flutter_install_all_ios_pods_file = File.join(File.dirname(File.realpath(__FILE__)), 'Flutter', 'podhelper.rb')
load flutter_install_all_ios_pods_file if File.exist?(flutter_install_all_ios_pods_file)

platform :ios, '15.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # This now works because we loaded the 'podhelper.rb' above
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Forces all plugins to match our iOS 15.0 target
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end